lang: de

project:
  type: book

  
book:
  title: "Angewandte Datenverarbeitung und Visualisierung (WiSe23/24)"
  subtitle: "WiSe23/24"
  author: "Daniela Palleschi"
  date: "9/7/2023"
  twitter-card: true
  downloads: [pdf, epub]
  chapters:
    - part: "Overview"
      chapters:
        - index.qmd
        - syllabus.qmd
        - setup/setup.qmd
    - part: "Course mats"
      chapters:
        - mats/01-intro_r.qmd
        - mats/02-quarto_1.qmd
        # - mats/03-dataviz_1.qmd
        # - mats/04-wrangling_1.qmd
        # - mats/05-code_stil.qmd
        # - mats/07-desc_stats.qmd
        # - mats/08-dateneinlesung.qmd
        # - mats/09-wrangling_2.qmd
        # - mats/10-dataviz_2.qmd
        # - mats/12-functions.qmd
        # - mats/13-infer_stats_1.qmd
        # - mats/14-dataviz_3.qmd
        # - mats/16-qna.qmd
    - part: "Berichte"
      chapters:
        - berichte/bericht_1.qmd
        - berichte/bericht_2.qmd
        - berichte/bericht_3.qmd
        
    - references.qmd


  navbar:
    right:
      - icon: home
        href: https://daniela-palleschi.github.io/
        text: D. Palleschi
      - icon: github
        href: https://github.com/daniela-palleschi/r4ling
        aria-label: Source Code
      - icon: life-preserver
        href: https://moodle.hu-berlin.de/course/view.php?id=119097
        aria-label: Course Moodle

bibliography: references.bib

crossref:
  exm-prefix: ex.   # (default is "Figure")
  # labels: alpha a        # (default is arabic)
  # subref-labels: alpha t # (default is alpha a)

format:
  html:
    toc: true
    number-sections: true
    include-after-body: custom.html
    code-tools: true
    page-layout: full
    self-contained: true
    theme:
      light: flatly
      dark: darkly
    execute:
      message: false
      warning: false
      echo: false
  # pdf:
  #   toc: true
  #   number-sections: true
  #   colorlinks: true
  #   code-overflow: wrap



