project:
  type: book

book:
  title: "Angewandte Datenverarbeitung und Visualisierung (WiSe23/24)"
  subtitle: "WiSe23/24"
  author: "Daniela Palleschi"
  date: "9/7/2023"
  date-format: "Vorlesung DD/MM/YY"
  twitter-card: true
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - intro.qmd
    - 'mats/00-kursuebersicht.qmd'
    - summary.qmd
    - references.qmd


  navbar:
    right:
      - icon: home
        href: https://daniela-palleschi.github.io/
        text: D. Palleschi
      - icon: github
        href: https://github.com/daniela-palleschi/ba-datenverarbeitung-wise23
        aria-label: Source Code
      - icon: life-preserver
        href: https://moodle.hu-berlin.de/course/view.php?id=119097
        aria-label: Course Moodle

bibliography: references.bib

crossref:
  exm-prefix: ex.   # (default is "Figure")
  # labels: alpha a        # (default is arabic)
  # subref-labels: alpha t # (default is alpha a)

format:
  html:
    toc: true
    number-sections: true
    include-after-body: custom.html
    code-tools: true
    page-layout: full
    self-contained: true
    theme:
      light: flatly
      dark: darkly
    execute:
      message: false
      warning: false
      echo: false



